networks:
  monitoring:
    driver: bridge

volumes:
  prometheus_data: 
  grafana_data: 

services:
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
    restart: unless-stopped
    networks:
      - monitoring

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    volumes:
      - grafana_data:/var/lib/grafana
    restart: unless-stopped
    networks:
      - monitoring

  node-exporter-golang:
    image: redhat/ubi9:latest
    container_name: node-exporter-golang
    # restart: unless-stopped
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command: 
      /bin/bash -c "
      yum install -y wget golang &&
      wget https://github.com/prometheus/node_exporter/releases/download/v1.8.1/node_exporter-1.8.1.linux-amd64.tar.gz &&
      tar xvfz node_exporter-1.8.1.linux-amd64.tar.gz &&
      cd node_exporter-1.8.1.linux-amd64 && ./node_exporter "
      # tail -f /dev/null"
    ports:
      - 9100:9100
      - 8080:8080
    networks:
      - monitoring