version: '3.8'

networks:
  monitoring:
    driver: bridge

volumes:
  prometheus_data: {}
  grafana_data: {}

services:
  monitoring:
    image: alpine:latest
    container_name: monitoring
    restart: unless-stopped
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
      - grafana_data:/var/lib/grafana
    command: >
      sh -c "
      apk add --no-cache prometheus grafana &&
      prometheus --config.file=/etc/prometheus/prometheus.yml --storage.tsdb.path=/prometheus &
      grafana-server --homepath=/usr/share/grafana --config=/etc/grafana/grafana.ini
      "
    ports:
      - "3000:3000"
      - "9090:9090"
    networks:
      - monitoring

  node-exporter-golang:
    image: alpine:latest
    container_name: node-exporter-golang
    restart: unless-stopped
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command: >
      sh -c "
      apk add --no-cache node-exporter go &&
      node_exporter --path.procfs=/host/proc --path.rootfs=/rootfs --path.sysfs=/host/sys --collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/) &
      sleep infinity
      "
    ports:
      - 8001
    expose:
      - 9100
    networks:
      - monitoring