networks:
  monitoring:
    driver: bridge

services:
  python-node-exporter:
    image: redhat/ubi9:latest
    container_name: python-node-exporter
    restart: unless-stopped
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command: >
      /bin/bash -c "
      yum install -y wget python3 python3-pip &&
      wget https://github.com/prometheus/node_exporter/releases/download/v1.8.1/node_exporter-1.8.1.linux-amd64.tar.gz &&
      tar xvfz node_exporter-1.8.1.linux-amd64.tar.gz &&
      cd node_exporter-1.8.1.linux-amd64 && ./node_exporter
      "
    
    ports:
      - 8000:8000
      - 9300:9100
    networks:
      - monitoring