version: '3.8'

networks:
  monitoring:
    driver: bridge

services:
  python-node-exporter:
    image: alpine:latest
    container_name: python-node-exporter
    restart: unless-stopped
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command: >
      sh -c "
      apk add --no-cache python3 py3-pip node-exporter &&
      node_exporter --path.procfs=/host/proc --path.rootfs=/rootfs --path.sysfs=/host/sys --collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/) &
      sleep infinity
      "
    
    ports:
      - 5003
    
    expose:
      - 9100
    networks:
      - monitoring